name: chai_shop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.5.0
  provider: ^6.0.5
  fluttertoast: ^8.2.1
  intl: ^0.18.0
  shared_preferences: ^2.1.1
  flutter_slidable: ^3.0.0
  badges: ^3.1.2  
  flutter_stripe: ^9.0.0
  url_launcher: ^6.1.10
  flutter_dotenv: ^5.0.2
  animations: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lint: ^1.7.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true